FROM php:7.3-rc-apache-stretch

# Install necessary dependencies
RUN apt-get update \
    && apt-get install -y git gnupg2 \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y build-essential nodejs

# Install Swagger
RUN git clone https://github.com/swagger-api/swagger-ui.git \
    && cd swagger-ui \
    && npm install \
    && npm run dev

# Configure apache mod rewrite
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

# Install composer.phar
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php & \
    && php -r "unlink('composer-setup.php');"
