FROM php:7.3-rc-apache-stretch

# Install necessary dependencies
RUN apt-get update \
    && apt-get install -y git gnupg2 \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y build-essential nodejs

# Configure apache mod rewrite
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load