version: '3.6'

services:

  # MySql Database
  slim_mysql:
    container_name: slim_mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: slim_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - slim_network

  # ElasticSearch server
  slim_elasticsearch:
    container_name: slim_elasticsearch
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    image: slim_elasticsearch
    networks:
      - slim_network

  # Apache + PHP7 server
  slim_app:
    container_name: slim_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: slim_app
    ports:
      - '80:80'
    networks:
      - slim_network

    # Bind mount the volume, so changes made in this directory will be recognized by the container
    volumes:
      - ./:/var/www/html/

networks:
  slim_network:
    name: slim_network
